sudo: false
language: node_js
node_js:
  - 14
install:
  - npm ci
cache:
  directories:
    - node_modules
branches:
  only:
    - main
notifications:
  email: false
script:
  - npm run lint
  - npm run build
